import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import HeaderPage from "@/components/header";
import MarquePage from "@/components/marque";
import { Bounce, ToastContainer } from "react-toastify";
import FooterPage from "@/components/Footer";
import { Suspense } from "react";

const hindSiliguri = Hind_Siliguri({
  subsets: ["bengali", "latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Bazar Dor App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: LayoutProps<"/">) {
  return (
    <html
      data-theme="light"
      lang="bn"
      className={`${hindSiliguri} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#F0F5F0]">
        <HeaderPage />

        <Suspense
          fallback={
            <div className="bg-white py-2 text-center text-sm">
              পণ্যের তথ্য লোড হচ্ছে...
            </div>
          }
        >
          <MarquePage />
        </Suspense>

        <main>
          {children}

          <ToastContainer
            position="top-right"
            autoClose={1000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            transition={Bounce}
          />
        </main>

        <FooterPage />
      </body>
    </html>
  );
}